// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NDCRegistration.Models;
//
//    var apiResponse = ApiResponse.FromJson(jsonString);

namespace NDCRegistration.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ApiResponse
    {
        [JsonProperty("Attendee no.")]
        public string AttendeeNo { get; set; }

        [JsonProperty("First Name")]
        public string FirstName { get; set; }

        [JsonProperty("Surname")]
        public string Surname { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("Mobile Phone")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long MobilePhone { get; set; }

        [JsonProperty("Job Title")]
        public string JobTitle { get; set; }

        [JsonProperty("Company")]
        public string Company { get; set; }

        [JsonProperty("Work Address 1")]
        public string WorkAddress1 { get; set; }

        [JsonProperty("Work Address 2")]
        public string WorkAddress2 { get; set; }

        [JsonProperty("Work City")]
        public string WorkCity { get; set; }

        [JsonProperty("Work County")]
        public string WorkCounty { get; set; }

        [JsonProperty("Work Postcode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long WorkPostcode { get; set; }

        [JsonProperty("Work Country")]
        public string WorkCountry { get; set; }
    }

    public partial class ApiResponse
    {
        public static ApiResponse FromJson(string json) => JsonConvert.DeserializeObject<ApiResponse>(json, NDCRegistration.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ApiResponse self) => JsonConvert.SerializeObject(self, NDCRegistration.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
